# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: mixed-line-ending
      - id: check-case-conflict
      - id: detect-private-key
      - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: bash -c 'PYTHONPATH=src uv run mypy --explicit-package-bases src/'
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ["-d", "relaxed"]
