"""Domain → taxonomy category mapping (high-confidence heuristic).

Pure data table — no logic lives here. Used by `classifier_core.py` as the
first-tier classifier (highest confidence).
"""

from __future__ import annotations

# Domain → category mapping (high confidence)
DOMAIN_RULES: dict[str, list[str]] = {
    "github.com": ["Programming", "DevEx"],
    "stackoverflow.com": ["Programming", "DevEx"],
    "gitlab.com": ["Programming", "DevEx"],
    "arxiv.org": ["Learning", "Papers"],
    "paperswithcode.com": ["AI", "Research"],
    "huggingface.co": ["AI", "Tools"],
    "pytorch.org": ["AI", "Tools"],
    "tensorflow.org": ["AI", "Tools"],
    "kaggle.com": ["AI", "Tools"],
    "figma.com": ["Design", "UI-UX"],
    "dribbble.com": ["Design", "UI-UX"],
    "awwwards.com": ["Design", "UI-UX"],
    "aws.amazon.com": ["Systems", "Cloud"],
    "cloud.google.com": ["Systems", "Cloud"],
    "azure.microsoft.com": ["Systems", "Cloud"],
    "docker.com": ["Systems", "Containers"],
    "kubernetes.io": ["Systems", "Containers"],
    "torproject.org": ["Security", "Privacy"],
    "medium.com": ["Learning", "Tutorials"],
    "dev.to": ["Programming", "DevEx"],
    "freecodecamp.org": ["Learning", "Courses"],
    "coursera.org": ["Learning", "Courses"],
    "udemy.com": ["Learning", "Courses"],
    "youtube.com": ["Learning", "Tutorials"],
    "twitter.com": ["Entertainment", "Social-Media"],
    "x.com": ["Entertainment", "Social-Media"],
    "reddit.com": ["Entertainment", "Social-Media"],
    "linkedin.com": ["Career", "Networking"],
    "indeed.com": ["Career", "Interview"],
    "glassdoor.com": ["Career", "Interview"],
    "coinbase.com": ["Quant", "Crypto-Trading"],
    "binance.com": ["Quant", "Crypto-Trading"],
    "etherscan.io": ["Blockchain", "Ethereum"],
    "coingecko.com": ["Quant", "Crypto-Trading"],
    "tradingview.com": ["Quant", "Strategies"],
    "investopedia.com": ["Learning", "Documentation"],
    "wikipedia.org": ["Reference", "Wikipedia"],
    "w3schools.com": ["Learning", "Cheatsheets"],
    "mdn.mozilla.org": ["Learning", "Documentation"],
    "caniuse.com": ["Web", "Web-Standards"],
    "npmjs.com": ["Programming", "DevEx"],
    "pypi.org": ["Programming", "Languages"],
    "crates.io": ["Programming", "Languages"],
    "news.ycombinator.com": ["Entertainment", "News"],
    "producthunt.com": ["Career", "Startups"],
    "angel.co": ["Career", "Startups"],
    "kickstarter.com": ["Career", "Startups"],
    "arduino.cc": ["Hardware", "Microcontrollers"],
    "raspberrypi.org": ["Hardware", "SBC"],
    "adafruit.com": ["Hardware", "Electronics"],
    "sparkfun.com": ["Hardware", "Electronics"],
    "expedia.com": ["Life", "Travel"],
    "booking.com": ["Life", "Travel"],
    "tripadvisor.com": ["Life", "Travel"],
    "allrecipes.com": ["Life", "Food"],
    "foodnetwork.com": ["Life", "Food"],
    "myfitnesspal.com": ["Life", "Health"],
    "strava.com": ["Life", "Health"],
    "spotify.com": ["Entertainment", "Streaming"],
    "soundcloud.com": ["Entertainment", "Streaming"],
    "ultimate-guitar.com": ["Life", "Hobbies"],
    "obsidian.md": ["Productivity", "PKM"],
    "notion.so": ["Productivity", "PKM"],
    "trello.com": ["Productivity", "Automation"],
    "proton.me": ["Security", "Privacy"],
    "eff.org": ["Security", "Privacy"],
    "nmap.org": ["Security", "Red-Team"],
    "grafana.com": ["Systems", "Observability"],
    "prometheus.io": ["Systems", "Observability"],
    "datadoghq.com": ["Systems", "Observability"],
    "linuxize.com": ["Systems", "Linux"],
    "archlinux.org": ["Systems", "Linux"],
    "gentoo.org": ["Systems", "Linux"],
    "debian.org": ["Systems", "Linux"],
}
